logdir: /home/msst/repo/Quantization/logs/llama2-7b/about_reassings/llama2_vecdim8_cbsize16384_A5e-5_C5e-5_lossL1_reassfrac0.1
model_name: Llama2-7b-hf
fp_blocks_path: /mnt/ssd_storage/ml/weights/vc_data/Llama2-7b-hf/per_block_fp
q_blocks_path: /mnt/ssd_storage/ml/weights/vc_data/Llama2-7b-hf/per_block_q/kmeans_l2_percoord


training_params:
  train_data:
    dataset_name: slim_pajama
    split: train[:2000]
    seq_length: 4096
    n_train_seq: &n_train_seq 384
    n_val_seq: 48
    batch_size: &batch_size 3

  validation_settings:
    val_before_trainig: True
    n_intermediate_val: 8

  optimization_settings:
    n_epochs: 2
    loss_fn: !L1

    method_params:
      reassine_params:
        #nn_search_dist: L2
        reassine_frac: 0.1
      use_latent_weight: True

    scheduler: &scheduler
      class: CosineAnnealingLR
      kwargs:
        T_max: 512

    optimizers:
      codebook_optimizer:
        param_label: codebook
        class: Adam
        kwargs:
          lr: 5e-5
        scheduler: *scheduler

      latent_optimizer:
        param_label: latent_weight
        class: Adam 
        kwargs:
          lr: 5e-5
        scheduler: *scheduler
