logdir: /home/msst/repo/Quantization/logs/llama2-7b/symquant/llama2_symquant_cb4096_vecdim16_C1e1_lossL1_SGD.yaml
model_name: Llama2-7b-hf
fp_blocks_path: /mnt/ssd_storage/ml/weights/vc_data/Llama2-7b-hf/per_block_fp
q_blocks_path: /mnt/ssd_storage/ml/weights/vc_data/Llama2-7b-hf/per_block_q/cb4096_vecdim16_weightPERCOORD_scaleOUTL2_distMSE_blocksizeNone_iters15_abscoords


training_params:
  train_data:
    dataset_name: slim_pajama
    split: train[:1500]
    seq_length: 4096
    n_train_seq: &n_train_seq 320 #256 #384
    n_val_seq: 50 #48
    batch_size: &batch_size 5

  validation_settings:
    val_before_trainig: True
    n_intermediate_val: 8

  optimization_settings:
    n_epochs: 4
    loss_fn: !LpLoss
      p: 1

    method_params:
      use_latent_weight: True
      reassine_params:
        reassine_frac: 0.0
        nlist: 256
        nprobe: 8

    scheduler: &scheduler
      class: CosineAnnealingLR
      kwargs:
        T_max: 256

    optimizers:
      codebook_optimizer:
        param_label: codebook
        class: SGD
        kwargs:
          lr: 5e1
        scheduler: *scheduler

