logdir: /home/msst/repo/Quantization/logs/llama2-7b/trellis/llama2_trellis_128seq_reassigns
model_name: Llama2-7b-hf
fp_blocks_path: /mnt/ssd_storage/ml/weights/vc_data/Llama2-7b-hf/per_block_fp
q_blocks_path: /mnt/ssd_storage/ml/weights/vc_data/Llama2-7b-hf/per_block_q/T256_L16_V2_K2_cbs10_LowBitSym_qtip
#qmodel_path: /home/msst/repo/Quantization/logs/checkpoints_Llama2-7b-hf/trellis/T256_L16_V2_K2_cbs10_LowBitSym_qtip 

training_params:
  train_data:
    dataset_name: slim_pajama
    split: train[:1500]
    seq_length: 4096
    n_train_seq: &n_train_seq 128
    n_val_seq: 32
    batch_size: &batch_size 2

  validation_settings:
    val_before_trainig: True
    n_intermediate_val: 8

  optimization_settings:
    n_epochs: 2
    loss_fn: !LpLoss
      p: 2

    method_params:
      use_latent_weight: True
      reassine_params:
        reassine_frac: 0.05
        reassine_step: 16

    scheduler: &scheduler
      class: CosineAnnealingLR
      kwargs:
        T_max: 256

    optimizers:
      latent_optimizer:
        param_label: latent_weight
        class: Adam 
        kwargs:
          lr: 5e-2 #1e-3
        scheduler: *scheduler
      
      scales_optimizer:
        param_label: scales
        class: Adam
        kwargs:
          lr: 5e-4
        scheduler: *scheduler

      SU_optimizer:
        param_label: SU
        class: Adam
        kwargs:
          lr: 5e-4
        scheduler: *scheduler

      SV_optimizer:
        param_label: SV
        class: Adam
        kwargs:
          lr: 5e-4
        scheduler: *scheduler

      norm_optimizer:
        param_label: norm
        class: Adam
        kwargs:
          lr: 5e-5
        scheduler: *scheduler
